function graphs = fr_requirecache(cfg)
%FR_REQUIRECACHE  Load the graph cache, with an actionable message if the
%   extraction stage has not been run yet.
    if ~exist(cfg.cacheFile, 'file')
        error('frgcn:noCache', ['\n\nThe graph cache does not exist yet:\n    %s\n\n' ...
            'Run the extraction stage first -- it builds the superpixel graphs\n' ...
            'and only has to be done once:\n\n' ...
            '    FRGCN_Extract\n\n' ...
            'Or just run the whole study in order:\n\n' ...
            '    FRGCN_Main\n'], cfg.cacheFile);
    end
    S = load(cfg.cacheFile);
    graphs = S.graphs;
end
